import type { DialogueLine } from './npcTypes'

/** One-line banter for wandering NPCs in After Hours — club vibe, no fake hints. */
export const CLUB_WANDERER_DIALOGUE_POOL: string[] = [
  'Not me. Keep dancing.',
  'Wrong Meebit. The bass is loud and so is my no.',
  'I am not your target. I am just vibing.',
  'No. This club is huge, and I am not the one.',
  'You want a different Meebit.',
  'Still looking? Wrong face.',
  'I am not the Meebit on your list tonight.',
  'Everyone looks sharp under neon. Still not me.',
  'I do not know who you need out here.',
  'Too many Meebits on this dance floor. I am not the right one.',
  'I came for the music, not to be found.',
  'Wrong Meebit. Keep moving.',
  'One target in the crowd. Not me.',
  'I am not the answer. Sorry.',
  'No wristband for being your target.',
  'Do not follow me. I am lost in the lights too.',
  'We all look the same when the strobes hit.',
  'Up close, every Meebit has their own night-out energy.',
  'Wrong fit. Wrong vibe. Wrong me.',
  'This club is loud, dark, and full of avatars.',
  'Neon, bass, and footsteps. That is the night.',
  'Still not me.',
  'Final answer: no.',
  'Absolutely not.',
  'No.',
  'Not me. That is all.',
  'Good luck out there.',
  'I am here, but I am not your target.',
  'Twenty thousand Meebits in the world. I am just one in the crowd.',
  'In After Hours, we walk, talk, and wait to be spotted.',
  'I am not the special Meebit tonight.',
  'Black and white still pops under purple light.',
  'I am small, but I am dressed for the club.',
  'Am I your friend? Maybe. Am I your target? No.',
  'Wrong Meebit. Nice try.',
  'Wrong face. Right club.',
  'Still not your target.',
  'Talk to another Meebit on the floor. Not me.',
  'The club has no name tags. That is the game.',
  'You are staring at the wrong avatar.',
  'Wrong Meebit, but this is a beautiful night.',
  'I like that you came to hunt in the dark.',
  'This floor is full of whispers and footsteps.',
  'Everyone is moving. Everyone is unique.',
  'Monochrome bodies, colorful lights.',
  'Still here? Still not me.',
  'Hard no.',
  'Nope.',
  'Not tonight.',
  'I belong in this club, but I am not your target.',
  'A Meebit rushed past near the bar. Not me though.',
  'I can walk and talk because this world was built for us.',
  'Just one face in a Saturday-night crowd.',
  'I am not the Meebit you want.',
  'Meebits do not snitch. House rules.',
  'My face looks familiar because we share the same world.',
  'I only walk on this dance floor.',
  'You talked to the wrong Meebit.',
  'I am not hiding. I am just in the mix.',
  'Look at me all you want. I am still not it.',
  'I am here for the night. This world is for playing.',
  'After Hours feels endless. I like that.',
  'Not the one. Never was.',
  'Go meet another avatar by the speakers.',
  'Wrong Meebit. Good chat though.',
  'I showed up when the museum lights went down.',
  'I am made of blocks, but my mood is real.',
  'Wrong number on the guest list.',
  'I like the fog and the glow.',
  'I am not your answer.',
  'Too many Meebits to scan in one song.',
  'I am looping the dance floor because this place is huge.',
  'Your guess is wrong. It is me saying no.',
  'I am not it.',
  'I saw many Meebits tonight. We all belong here.',
  'Wrong conversation partner.',
  'This hunt is hard because the crowd never stops.',
  'No directions from me. I am just a walker.',
  'I am innocent and very blocky.',
  'Wrong Meebit. Good effort.',
  'Hello. Goodbye. Wrong Meebit.',
  'I am polite, but I am not the target.',
  'Come back later. I will still be moving.',
  'Near the DJ booth the music hits different. Still not me.',
  'The bar glows pink on one side and blue on the other.',
  'VIP couches look comfy. I am not on your list.',
  'Those speaker stacks are loud. So is my no.',
  'Neon signs everywhere. None of them say my number.',
  'I saw someone lingering by a dark statue. Was not me.',
  'The entrance arch is bright. I am deeper inside.',
  'Spotlights make every Meebit look famous for a second.',
  'Partition walls split the floor. I am on the wrong side of your guess.',
  'Wrong Meebit. Enjoy the night anyway.',
]

export const CLUB_CREATOR_DIALOGUE_LINES: DialogueLine[] = [
  {
    id: 'shawn-club-1',
    text: 'The museum closes. After Hours is where Meebits keep moving.',
    category: 'world',
  },
  {
    id: 'shawn-club-2',
    text: 'I wanted a second room with louder energy and softer light.',
    category: 'world',
  },
  {
    id: 'shawn-club-3',
    text: 'Same hunt, different mood. Neon, bass, and a bigger crowd.',
    category: 'world',
  },
  {
    id: 'shawn-club-4',
    text: 'Meebits look different under club lights. That is part of the fun.',
    category: 'meebits',
  },
  {
    id: 'shawn-club-5',
    text: 'Talk to people near the bar, the DJ booth, and the VIP couches. Someone might slip you a hint.',
    category: 'hint',
  },
  {
    id: 'shawn-club-6',
    text: 'I put statues in the dark so the floor feels alive even when the crowd thins.',
    category: 'world',
  },
  {
    id: 'shawn-club-7',
    text: 'After Hours is not a sequel. It is the same world staying open late.',
    category: 'world',
  },
  {
    id: 'shawn-club-8',
    text: 'Every Meebit here is still an identity, not just a silhouette in the fog.',
    category: 'meebits',
  },
]

export const CLUB_TARGET_FOUND_LINES = [
  'You found me in the dark. Sharp eyes.',
  'Caught me under the lights. Nice one.',
  'You pulled me out of the crowd. Good hunt.',
  'Found me. The club is loud, but you listened.',
] as const
