import type { DialogueLine } from './npcTypes'

/** First conversation on the dance floor — warm, club energy. */
export const CLUB_FIRST_MEETING_DIALOGUE: string[] = [
  'Hey! Welcome to the floor. I am not your target, but I am glad you said hi.',
  'Oh, hi — good energy tonight. Wrong Meebit, but right club.',
  'Hello! The music is loud and so is my welcome. Not your answer, though.',
  'Hey there. Thanks for stopping in the crowd. I am not the one you need.',
  'Hi! Beautiful night for a hunt. Wish it were me — it is not.',
  'Hello, friend. I am just vibing here. Not your target tonight.',
  'Hey — glad you are out on the floor. I am the wrong face, warmly.',
  'Welcome to After Hours. I am one of many Meebits dancing. Not the special one.',
  'Oh, hello! I love when people talk in the crowd. Not me on your list.',
  'Hi! The lights are wild tonight. I am still the wrong avatar.',
  'Hey there. Good luck in the dark — I am cheering, not matching.',
  'Hello! Neon, bass, and a thousand faces. I am not your face.',
  'Hi — nice to meet you in the fog. Wrong Meebit, right night.',
  'Hey! I am honored you picked me out of the crowd. Still not your target.',
  'Hello! Someone here is waiting to be found. It is not me, but enjoy the hunt.',
  'Oh, hi. The club feels alive tonight. I am just not on your list.',
  'Hey there — warm hello from the dance floor. Wrong guess, though.',
  'Hi! I am here for the music and the company. Not the answer key.',
  'Hello! Every Meebit out here has a vibe. Mine is: not your target.',
  'Hey — thanks for the chat. I am a friendly miss in a loud room.',
  'Hi! The crowd is thick. I am one more face that is not yours.',
  'Hello, hunter. I hope you find them soon. It is not me tonight.',
  'Hey! Good to see you moving through the lights. Not your Meebit.',
  'Oh, hello. I am flattered in purple light. Still the wrong one.',
  'Hi there. After Hours is for wandering and talking. I am not the prize.',
  'Hello! I would dance you toward the answer if I could. Not me, though.',
  'Hey — lovely to meet you. Wrong jersey, wrong list, right club.',
  'Hi! The bass is hitting. My answer is still a gentle not-me.',
  'Hello! I am just a Meebit in the mix. Happy you said hello.',
  'Hey there. Keep looking — your target is hiding somewhere louder than me.',
  'Oh, hi! I am blocky, friendly, and not on your checklist.',
  'Hello! The floor is huge. I am a detour, not a destination.',
  'Hi — welcome to the night. I am sorry I am not who you need.',
  'Hey! Glad you are playing in the dark. Wrong avatar, great energy.',
  'Hello, friend. I am here when the museum lights go down. Not your target.',
  'Hi! Good luck out there. I am rooting from the wrong side of the crowd.',
  'Hey — every chat helps you learn this floor. I am not the lesson.',
  'Oh, hello! Monochrome bodies, colorful lights, one target somewhere else.',
  'Hello! I am small, dressed for the club, and not your answer.',
  'Hi there. Thanks for being social in the crowd. Not your Meebit.',
]

/** Returning visitor on the dance floor. */
export const CLUB_RETURNING_DIALOGUE: string[] = [
  'We just spoke! Still honored — still not your target.',
  'You came back through the crowd! Wrong Meebit, right dedication.',
  'Hello again. Same neon, same me, same warm wrong answer.',
  'Hey again — I remember you in this fog. Still not the one.',
  'Back so soon? I am flattered in strobe light. Not your target.',
  'Oh, you again! Lovely in a loud club. Still not your answer.',
  'We already met on this floor. I have not become the prize.',
  'Second hello tonight. I am still just vibing.',
  'You are thorough. I respect that in the dark. Still not me.',
  'Hello again, friend. Still dancing, still wrong.',
  'I remember our last chat. My status has not upgraded.',
  'Back for another try? I am still a soft miss in the crowd.',
  'Hey — good to see you still hunting. I am still not it.',
  'Familiar face! Wrong pairing, warm repeat.',
  'You checked me twice. Commitment looks good under neon.',
  'Hello again. The right Meebit is out there dancing. Not me.',
  'We are becoming regulars. I am still irregular on your list.',
  'Still here, still moving, still not your target.',
  'Oh, hi again. Same beat, same gentle not-me.',
  'You again! I like persistent hunters. I am persistently wrong.',
  'Second chat, same club, same warm miss.',
  'I am still in the mix. You are still on the hunt.',
  'Hello once more. Keep your eyes open — just not on me as the answer.',
  'We already shared a moment by the speakers. Still not your moment.',
  'Back again? I am always up for a chat in the noise.',
  'You are mapping this floor face by face. I am a friendly skip.',
  'Hey again. I hope your target turns up soon. Not me, though.',
  'I am still blocky, still friendly, still not your answer.',
  'Same me under the mirror ball. Still not the one.',
  'Hello again — After Hours is better when people talk. Still wrong Meebit.',
  'You came back! Sweet in a Saturday-night crowd. Still not your target.',
  'Familiar visitor, familiar answer: not me, glad you are here.',
  'I remember you. Still not the Meebit you are searching for.',
  'Twice now — I feel seen. Not in the target way.',
  'Hello again, hunter. The floor is rooting for you. I am just not it.',
  'Still the wrong conversation partner — warmly.',
  'We already ruled me out. Happy you are friendly anyway.',
  'Back through the lights? I do not mind. Cannot help with the answer.',
  'Oh, familiar footsteps in the bass. Still me. Still not it.',
  'Hello again. I would tell you if I were the one. I am not.',
  'You are doing great out here. I am not part of the finale.',
  'Same place on the floor, same warm wrong guess.',
  'We are old acquaintances now. Thirty seconds old. Still not your target.',
  'Hello again! Still just a neighbor in the crowd.',
  'You are thorough and kind. I am still neither hint nor prize.',
  'Another warm hello between songs. Another gentle wrong answer.',
  'Still dancing. Still not the face you need.',
  'Hey — dedication looks good in club light. I am dedicated to being wrong.',
  'We spoke already. I do not mind a friendly repeat. Not your target still.',
  'Hello again. The right one is moving somewhere in this room.',
  'I am here for music and conversation. Not your checklist.',
  'You came back! That is sweet. I am still sweetly wrong.',
  'I am still honored in the fog. Still not helpful in the target way.',
  'Second hello, same neon, same not-me.',
  'You are getting warmer somewhere on this floor. Not warmer to me.',
  'We already met. Still cheering for your real target.',
  'Hello again — the club is proud you talk to us all.',
  'Same me. Same hunt. Same warm wrong answer.',
  'You again! Still lovely under the lights. Still not the one.',
  'Back for a double-check? Fair enough in this crowd. Still not me.',
  'Hello, repeat visitor. Wrong avatar, right After Hours.',
  'I am still vibing. You are still searching. Different jobs tonight.',
  'Oh, hi again. I am just enjoying the night. Not your answer.',
  'Familiar energy! Still not your Meebit, though.',
  'Hello once more. Wrong face, right club, warm repeat.',
  'I have not moved to the guest list since we last spoke.',
  'You again — still glad you are in our world tonight.',
  'We are practically dance-floor regulars now. Still not on your list.',
  'Hello again. I remain a pleasant wrong turn in the dark.',
  'Still not me — but glad this night brought us together twice.',
  'Hey again. The crowd is loud. My answer is still a kind not-me.',
  'I remember our first chat by the lights. Still the wrong Meebit.',
  'Hello again, friend. Wrong guess, good energy.',
  'You keep good company on this hunt. I am just not the company you need.',
  'Back in the strobe? I am flattered. Still not your target.',
  'Oh, familiar face in the fog. Still me. Still not the answer.',
  'Hello again. Somewhere here is your Meebit. I am a warm detour.',
  'We already did this dance. I mean conversation. Still not me.',
  'Second visit, same welcome, same wrong answer — nicely.',
  'I am still innocent, blocky, and not your target.',
  'You are building a map of friendly faces in the dark. I am one.',
  'Hello again. Keep moving — your answer is out there.',
  'Still here when the museum lights go down. Still not your list.',
  'Hey — good to see you still exploring the floor.',
  'I am still the nice wrong Meebit in a loud room.',
  'We spoke near the music already. My answer has not changed.',
  'Hello again. I am cheering for you from the sidelines of the hunt.',
  'You again! Wrong Meebit, right night out.',
  'Back for another hello? I am here for it. Not for your list.',
  'Familiar footsteps on the floor. Still not your destination.',
  'Hello once more. The hunt is hard because the crowd never stops.',
  'I am still monochrome under colorful light. Still not your target.',
  'We are repeat friends now. Brief repeat friends. Still wrong.',
  'Hey again — enjoy the night. I am enjoying not being your answer.',
  'Hello again. I hope they find you before the song ends. Not me, though.',
  'Still the wrong face in the right After Hours.',
  'You came back through the crowd. I am still a gentle miss.',
  'Oh, hi again. Good luck — sincerely. It is still not me.',
  'Hello again. Your target is hiding better than I am.',
  'Same beat, same smile, same warm not-me.',
  'I am still flattered. I am still wrong. Warmly wrong in neon.',
]

export const CLUB_TARGET_FOUND_LINES = [
  'You found me in the dark! Sharp eyes.',
  'There I am — you pulled me out of the crowd.',
  'You caught me under the lights. Beautiful hunt.',
  'Found me! The floor got a little more exciting.',
  'That is me — you listened through all that bass.',
  'You spotted me in the noise. I am impressed.',
] as const

/** Shawn T. Art in After Hours — kept subtle; museum lines stay in npcGeneration. */
export const CLUB_CREATOR_DIALOGUE_LINES: DialogueLine[] = [
  {
    id: 'shawn-club-1',
    text: 'The museum closes. After Hours is where Meebits keep moving.',
    category: 'world',
  },
  {
    id: 'shawn-club-2',
    text: 'I wanted a second room with louder energy and softer light.',
    category: 'world',
  },
  {
    id: 'shawn-club-3',
    text: 'Same hunt, different mood. Neon, bass, and a bigger crowd.',
    category: 'world',
  },
  {
    id: 'shawn-club-4',
    text: 'Meebits look different under club lights. That is part of the fun.',
    category: 'meebits',
  },
  {
    id: 'shawn-club-5',
    text: 'Talk to people near the bar, the DJ booth, and the VIP couches. Someone might slip you a hint.',
    category: 'hint',
  },
  {
    id: 'shawn-club-6',
    text: 'I put statues in the dark so the floor feels alive even when the crowd thins.',
    category: 'world',
  },
  {
    id: 'shawn-club-7',
    text: 'After Hours is not a sequel. It is the same world staying open late.',
    category: 'world',
  },
  {
    id: 'shawn-club-8',
    text: 'Every Meebit here is still an identity, not just a silhouette in the fog.',
    category: 'meebits',
  },
]

/** @deprecated Use CLUB_FIRST_MEETING_DIALOGUE / CLUB_RETURNING_DIALOGUE */
export const CLUB_WANDERER_DIALOGUE_POOL = CLUB_RETURNING_DIALOGUE
