/** One-line banter for wandering NPCs — no fake directions or hint-like advice. */
export const WANDERER_DIALOGUE_POOL: string[] = [
  'Not me. Keep walking.',
  'Wrong Meebit. Nice try though.',
  'I am not your target. I am just vibing.',
  'Nope. The gallery is huge and I am humble.',
  'You want someone else. Probably someone cooler.',
  'Still hunting? Cool hobby. Wrong avatar.',
  'My silhouette is iconic. Your target\'s is different.',
  'Check the crowd again. I believe in you.',
  'I blend in on purpose. It is called fashion.',
  'Every Meebit looks guilty in black and white.',
  'I would help, but I literally cannot.',
  'The museum is full of decoys. I am the decoy-est.',
  'I am just here for the art. And the walking.',
  'Wrong avatar. Keep moving, detective.',
  'Hundreds of us. One of them is right. Spoiler: not me.',
  'I am a distraction. You are welcome.',
  'No label on my back. Museum policy.',
  'Do not follow me. I have no sense of direction.',
  'We all look the same from far away. Tragic, really.',
  'Silhouettes lie. Especially mine.',
  'VRM details matter. Mine say "not it."',
  'Hat shape. Shoe shape. Vibe. All wrong for your quest.',
  'I am not wearing that target outfit. Wardrobe malfunction avoided.',
  'Wrong shoes. Wrong hat. Wrong me. Right museum.',
  'This gallery never ends. Neither does my confidence.',
  'Black, white, and confusion. Name of my autobiography.',
  'Still not me, champion.',
  'Go bother another voxel.',
  'I refuse to be your answer. Boundaries.',
  'Wrong Meebit, right museum.',
  'Art critic says: not the target. Ten out of ten wrong.',
  'My vibe is off-brand for you.',
  'I am plain sight. Still wrong. Still handsome.',
  'No hints from me. Museum rules. Also I do not know.',
  'The rule board says no labels. I obey.',
  'You are staring at the wrong ghost. Polite ghost, though.',
  'Wrong ghost, cool museum.',
  'I like your urgency though. Very flattering.',
  'Gallery acoustics are weird. So is my outfit.',
  'Footsteps everywhere. Drama everywhere.',
  'Everyone is walking, no one is sure. Peak Meebits.',
  'Monochrome chaos. My favorite genre.',
  'Still here? Still not your target.',
  'Final answer: no.',
  'Absolutely not.',
  'Hard pass.',
  'Negative.',
  'Move along, detective.',
  'Case closed on me.',
  'Open case elsewhere.',
  'Good luck, hunter.',
  'I am in here. Wrong place. Great face.',
  'Twenty thousand siblings and none of them brought snacks.',
  'My metadata says chill. My walk cycle says panic.',
  'Licensed for personal use. Unlicensed for your guessing game.',
  'I am literally a PNG with legs.',
  'Floor price of my dignity: still holding.',
  'Trait: wrong answer. Rarity: common.',
  'They minted 20,000 of us and only one is special today. Not me.',
  'Voxel life chose me. Your target did not.',
  'Black and white because color would make this too easy.',
  'My polygon count is low but my confidence is high.',
  'Companion? No. Competition? Also no.',
  'I export for free but my time is not free.',
  'Ask the chain. It does not know either.',
  'I was generated, not selected. Story of my life.',
  'My rig is ready. My alibi is stronger.',
  'Somewhere in the metadata it says "not your guy."',
  'I have more triangles than clues.',
  'Larva Labs made me cute. You made this awkward.',
  'Procedural face, procedural excuses.',
  'I am token #something. You need token #something else.',
  'Minted in 2021. Still wandering in 2026.',
  'My hat is a lifestyle choice, not a clue.',
  'Shoes say nothing. Mouth says "not me."',
  'I am 60% voxels, 40% denial.',
  'Community pass? I barely passed standing still.',
  'You picked the wrong NPC. Classic rookie move.',
  'I would cosplay your target but the hat does not fit.',
  'Wrong Meebit energy. Right museum energy.',
  'My emote is shrug. My line is no.',
  'Gas fees were high. My patience is low.',
  'On-chain proof I am not it: you are talking to me.',
  'IRL me is fine. In-game me is also not the answer.',
  'Someone sprinted past earlier. They looked motivated. Unlike me.',
  'If I were the target I would have run by now.',
  'Collect them all? Sure. Find them all? Your problem.',
  'I am an NFT with a walk cycle and zero responsibility.',
  'My rarity is "background character."',
  'Trait roll: sarcasm. Legendary.',
  'You need glasses. Or a better memory. Not me.',
  'I am the Meebit your Meebit warned you about. Still wrong.',
  'Gallery NPC union forbids snitching. Solidarity.',
  'I could lie for fun but lying is extra.',
  'Wrong number on the jersey. I do not wear jerseys.',
  'My face is familiar because we are all familiar.',
  'Touch grass? I touch floor tiles. Same thing.',
  'Speedrun strats do not include chatting with me.',
  'I am side quest energy in a main quest museum.',
  'Achievement unlocked: Talked To Wrong Meebit.',
  'Your target has better timing. I have better jokes.',
  'I am not hiding. I am loitering.',
  'Scan me all you want. Result: no.',
  'Wrong turn, right vibe.',
  'I am the comic relief. They are the plot.',
  'Meebits museum hours: eternal. My patience: limited.',
  'I woke up, chose violence against your guess.',
  'Not the one. Never was. Never will be.',
  'Go touch another avatar. Politely.',
  'I am three blocks tall and zero blocks helpful.',
  'Wrong Meebit. Right conversation. Debatable.',
]
