/** First conversation — warm hello, gentle wrong-target. */
export const MUSEUM_FIRST_MEETING_DIALOGUE: string[] = [
  'Oh, hello! I do not think I am the one you are looking for, but it is lovely to meet you.',
  'Hey there — welcome to the gallery. I am afraid I am not your target, though.',
  'Hi! Beautiful day for a hunt. Wish I could help, but it is not me.',
  'Hello, friend. I am just wandering through the museum. Not your Meebit, I am sorry.',
  'Good to see a visitor. I hope you find who you need — it is not me today.',
  'Hey! Thanks for stopping by. Wrong face, but I am glad you said hello.',
  'Welcome to the gallery. I am one of many Meebits here, and not the special one today.',
  'Oh, you are searching? I will cheer you on. Just not from the answer key.',
  'Hi there. The museum is big and full of friends. I am not the one on your list.',
  'Hello! I love when people explore this place. I am not your target, sadly.',
  'Hey — nice to meet you. I am just enjoying the quiet floors. Wrong Meebit, though.',
  'Good afternoon. I am honored you picked me to talk to. Still not your target.',
  'Hello! Every Meebit here has a story. Mine is simply: not the one you need.',
  'Hi! The gallery feels peaceful today. I am not who you are hunting for.',
  'Oh, hello. I have been walking these halls all day. Not your answer, I am afraid.',
  'Hey there. Black and white everywhere, and one target somewhere. Not me.',
  'Welcome! I am happy to chat. I just cannot be the Meebit you are looking for.',
  'Hi! Someone out there is waiting to be found. It is not me, but good luck.',
  'Hello, traveler. This museum is a good home for Meebits. I am not your target today.',
  'Hey — glad you are playing in our world. Wrong avatar, right gallery.',
  'Hi! I am just a walker in the crowd. Lovely to meet you. Not your Meebit.',
  'Hello! I was admiring the sculptures. I am not the face on your list.',
  'Oh, hi. You have a kind way of approaching people. I am still the wrong one.',
  'Hey there. The hunt is part of the fun. I am not the prize, though.',
  'Hello! I am a small Meebit in a big museum. Happy to talk — not your target.',
  'Hi! Good luck out there. I am rooting for you from the wrong side of the guess.',
  'Welcome to the museum. I am here for the art and the company. Not the answer.',
  'Hey — every conversation helps you learn this place. I am not the one, though.',
  'Hello! I feel lucky to walk here. I am sorry I am not who you need.',
  'Hi there. The gallery echo makes every step sound important. Not my step, though.',
  'Oh, hello! I am flattered. Wrong Meebit, but this museum is full of right ones.',
  'Hey. Thanks for the hello. I am not on your list, but I am glad you are here.',
  'Hello, friend. Meebits belong in worlds like this. I am just not today\'s target.',
  'Hi! Keep looking — someone here is special to you. It is not me.',
  'Good to meet you. I will be walking nearby if you need company. Not a hint, though.',
  'Hello! The museum has no labels on purpose. I am not the label you want.',
  'Hey there — warm welcome. I am the wrong face, but the right world.',
  'Hi! I am made of blocks and good intentions. Not your target, I am afraid.',
  'Oh, hi. I love that you talk to Meebits instead of just scanning faces. Still not me.',
  'Hello! Somewhere in this gallery is your answer. I am just a friendly detour.',
]

/** Returning visitor — remembers you, stays warm. */
export const MUSEUM_RETURNING_DIALOGUE: string[] = [
  'We just spoke! I am still honored — and still not your target.',
  'You came back to me! I appreciate that. Wrong Meebit, as before.',
  'Hello again. I have not moved far. I have also not become your answer.',
  'Still hunting? I am cheering for you. Just from the sidelines.',
  'Back so soon? I am flattered. Still the wrong face, though.',
  'Hey again — I remember you. I am afraid my answer has not changed.',
  'Oh, you again! Lovely to see a familiar visitor. Not the one you need.',
  'We already met! I am glad the museum feels worth revisiting. Not me, though.',
  'Second hello of the day. I am still just a Meebit in the crowd.',
  'You are dedicated. I respect that. I am still not your target.',
  'Hello again, friend. I have been walking in circles. Still not your circle.',
  'Back for another chat? I am here for it. Not here for your list, though.',
  'I remember you from a moment ago. Sweet of you to return. Wrong Meebit still.',
  'Still searching the gallery? Me too, in my own way. Not searching for me, though.',
  'Hey — good to see you again. I wish I had better news. It is still not me.',
  'You are thorough. I like that. I am consistently not the answer.',
  'Another visit! The museum is better when people talk. I am still the wrong one.',
  'We have met before, briefly. I am still just enjoying the floors.',
  'Hello again. I will never tire of visitors. I will also never be your target.',
  'You keep good company on this hunt. I am just not the company you need.',
  'Oh, hi again. Same hat, same shoes, same wrong Meebit.',
  'Second time is just as charming. Still not your guy, though.',
  'Second time is just as charming. Still not your girl, though.',
  'I am still walking. You are still looking. We are still not a match.',
  'Familiar face! Mine, I mean. Yours too. Wrong pairing, though.',
  'You checked me twice — that is commitment. I am still not it.',
  'Hello again. The gallery is huge. I am still not the Meebit you want.',
  'We already ruled me out. I am happy you are friendly anyway.',
  'Back again? I do not mind. I mind only that I cannot help with the answer.',
  'Still me, still not your target. Thanks for the company, though.',
  'I have not hidden. I have not changed. I am still the wrong conversation.',
  'You are getting to know this museum well. I am a repeat, not a result.',
  'Hello once more. I am a terrible secret keeper because I am not the secret.',
  'Same Meebit, same warm no — if that makes sense. Not your target.',
  'I am starting to feel like an old friend. An old wrong friend.',
  'You came back! That means you are careful. I am still carefully not the one.',
  'Another hello in these quiet halls. Still not your answer.',
  'We are becoming regulars to each other. I am still irregular on your list.',
  'Hey again. I hope the right Meebit is nearby. It is not me.',
  'Good to see you still exploring. I remain a pleasant wrong turn.',
  'You are mapping this place one chat at a time. I am not the destination.',
  'Hello again — I am still flattered, still wrong.',
  'I remember our last chat. My status has not upgraded to target.',
  'Still here, still walking, still not the Meebit you need.',
  'You are kind to talk to so many of us. I am one of the friendly misses.',
  'Back for a double-check? Fair enough. Still not me.',
  'Twice now — I feel seen. Not in the target way, though.',
  'Hello again, hunter. The museum is rooting for you. I am just not it.',
  'I am still the same blocky face you met earlier. Wrong one, warmly.',
  'You again! I like persistent people. I am persistently not your target.',
  'We already did this. I am still happy you are in our world.',
  'Second chat, same answer: lovely to meet you, not your Meebit.',
  'I am still admiring the gallery. You are still on the hunt. Different jobs.',
  'Oh, familiar footsteps. Still me. Still not the answer.',
  'Hello again. I would tell you if I were the one. I am not.',
  'You are doing great. I am just not part of the great finale.',
  'Back so soon? The museum feels alive when people talk. Still wrong Meebit.',
  'I am honored you remembered me. I am sorry I am still not helpful.',
  'Same place, same smile, same wrong guess — warmly.',
  'We are old acquaintances now. Ten seconds old. Still not your target.',
  'Hello again! I am still just a neighbor in the crowd.',
  'You are thorough and kind. I am still neither the hint nor the prize.',
  'I have not become famous since we last spoke. Still not on your list.',
  'Another warm hello. Another gentle wrong answer.',
  'Still walking these halls. Still not the face you need.',
  'Hey — good to see dedication. I am dedicated to being the wrong Meebit.',
  'We spoke already, but I do not mind a friendly repeat. Not your target still.',
  'Hello again. The right one is out there. I am the nice wrong one.',
  'I am still here for art and conversation. Not for your checklist.',
  'You came back! That is sweet. I am still sweetly wrong.',
  'Familiar visitor, familiar answer: not me, but glad you are here.',
  'I remember you. I am still not the Meebit you are searching for.',
  'Hello once more. Keep your eyes open — just not on me as the answer.',
  'We already shared a moment. I am still the wrong moment.',
  'Second hello, same gallery, same warm not-me.',
  'You are mapping faces fast. I am one you can skip next time.',
  'Oh, hi again. I am still just enjoying being a Meebit here.',
  'Back again? I am always up for a chat. Never up for being the target.',
  'Hello, repeat visitor. I am still the wrong avatar in the right museum.',
  'I am still blocky, still friendly, still not your answer.',
  'You are getting warmer somewhere. Not warmer to me, though.',
  'We already met. I am still cheering for your real target.',
  'Hello again — the museum is proud of you for talking to us all.',
  'Same me. Same hunt. Same warm wrong answer.',
  'I have not moved to the answer key since last time.',
  'You again! Still lovely. Still not the one.',
  'I am starting to recognize your footsteps. Still not recognizing myself as your target.',
  'Hello again, friend. Wrong Meebit, right world.',
  'We are practically regulars now. I am still irregular on your hunt.',
  'I am still honored. I am still wrong. Warmly wrong.',
  'Back for another try? I am still a soft miss, not a hit.',
  'Hello again. I hope your target says hi soon. It will not be me.',
  'You are building a map of friendly faces. I am one of them.',
  'Still not me — but I am glad this place brought us together twice.',
]

export const MUSEUM_TARGET_FOUND_LINES = [
  'You found me! What a keen eye.',
  'There I am — you caught me fair and square.',
  'You found me in the crowd. Beautiful work.',
  'That is me! I knew you would get here.',
  'You spotted me. I am impressed.',
  'Found me! The gallery got a little more exciting.',
] as const

/** @deprecated Use MUSEUM_FIRST_MEETING_DIALOGUE / MUSEUM_RETURNING_DIALOGUE */
export const WANDERER_DIALOGUE_POOL = MUSEUM_RETURNING_DIALOGUE
