/** One-line banter for wandering NPCs — simple English, Meebits world flavor, no fake hints. */
export const WANDERER_DIALOGUE_POOL: string[] = [
  'Not me. Keep walking.',
  'Wrong Meebit. Try again.',
  'I am not your target. I am just walking here.',
  'No. This museum is big, and I am not the one.',
  'You want a different Meebit.',
  'Still looking? Wrong Meebit.',
  'I am not the Meebit on your list.',
  'I look like everyone else here. Sorry.',
  'Every Meebit looks similar in black and white.',
  'I do not know who you need.',
  'There are many Meebits in this gallery. I am not the right one.',
  'I am here for the art. And for walking.',
  'Wrong Meebit. Keep moving.',
  'Many Meebits live in this museum. One is special today. Not me.',
  'I am not the answer. Sorry.',
  'No name tag on my back. That is the museum rule.',
  'Do not follow me. I am lost in the gallery too.',
  'We all look the same from far away.',
  'Up close, every Meebit is a little different.',
  'Wrong hat. Wrong shoes. Wrong me.',
  'This museum is very big and very quiet.',
  'Black, white, and footsteps. That is daily life here.',
  'Still not me.',
  'Final answer: no.',
  'Absolutely not.',
  'No.',
  'Not me. That is all.',
  'Good luck in the gallery.',
  'I am here, but I am not your target.',
  'There are twenty thousand Meebits in the world. I am just one.',
  'In this world, we walk, talk, and wait to be found.',
  'I am not the special Meebit today.',
  'Black and white makes every face feel familiar.',
  'I am small, but I am proud to be a Meebit.',
  'Am I your friend? Maybe. Am I your target? No.',
  'Wrong Meebit. Nice try.',
  'Wrong face. Right museum.',
  'Still not your target.',
  'Talk to another Meebit. Not me.',
  'The gallery has no labels. That is on purpose.',
  'You are looking at the wrong avatar.',
  'Wrong Meebit, but this is a beautiful museum.',
  'I like that you came to play in a Meebit world.',
  'This gallery is full of footsteps and whispers.',
  'Everyone is walking. Everyone is unique.',
  'Black and white everywhere. Color lives inside each Meebit.',
  'Still here? Still not me.',
  'Hard no.',
  'Nope.',
  'Not today.',
  'I belong in this museum, but I am not your target.',
  'A Meebit ran past earlier. We all love to walk.',
  'I can walk and talk because this world was made for us.',
  'I am just one face in a crowd of avatars.',
  'I am not the Meebit you want.',
  'Meebits do not snitch. That is our culture.',
  'My face looks familiar because we share the same world.',
  'I only walk on this gallery floor.',
  'I am a tiny identity in a big museum.',
  'You talked to the wrong Meebit.',
  'I am not hiding. I am just being myself.',
  'Look at me all you want. I am still not it.',
  'I am here for fun. This world is for playing.',
  'This museum feels endless. I like that.',
  'Not the one. Never was.',
  'Go meet another avatar in the crowd.',
  'Wrong Meebit. Nice chat though.',
  'I woke up in this world and chose to walk.',
  'I am made of blocks, but my mood is real.',
  'Wrong number on the jersey. Wait, I have no jersey.',
  'I like this monochrome gallery.',
  'I am not your answer.',
  'Too many Meebits to count in one afternoon.',
  'I am walking in circles because this place is huge.',
  'Your guess is wrong. It is me.',
  'I am not it.',
  'I saw many Meebits today. We all belong here.',
  'Wrong choice of conversation partner.',
  'This hunt is hard because we all belong together.',
  'No directions from me. I am just a walker.',
  'I am innocent and very blocky.',
  'Wrong Meebit. Good effort.',
  'Hello. Goodbye. Wrong Meebit.',
  'I am polite, but I am not the target.',
  'Come back later. I will still be walking.',
  'A Meebit is more than a picture. We live here now.',
  'This gallery is a home for twenty thousand faces.',
  'My hat is part of who I am.',
  'My shoes are part of my story.',
  'Shawn built this place so Meebits could be seen.',
  'In the metaverse, a Meebit can stand in a world like this.',
  'We are avatars with legs and opinions.',
  'Some Meebits are loud. I am calm.',
  'Some Meebits are weird. I am proudly normal.',
  'The museum has no signs because memory is part of the game.',
  'Black walls, white floor, many Meebits.',
  'I was made to be used in worlds like this one.',
  'Every block on my body has a reason.',
  'I am pixel art that learned to walk.',
  'This is not just a collection. It is a place.',
  'I feel lucky to walk in a Meebit museum.',
  'We are all siblings in a family of twenty thousand.',
  'My world is simple: walk, talk, belong.',
  'A quiet Meebit is still a full Meebit.',
  'I am not famous. I am still important.',
  'The gallery echo makes every step sound big.',
  'Monochrome does not mean boring.',
  'I carry my identity in my shape and my walk.',
  'Not your guy.',
  'Not your girl.',
  'Not your Meebit.',
  'Wrong Meebit. The museum goes on.',
  'I am part of the crowd, not the answer.',
  'Being a Meebit means being ready for new worlds.',
  'I love that someone built a game inside our world.',
  'We were born as art. Now we are neighbors.',
  'I have no map. I have this floor.',
  'Every visitor remembers a different face.',
  'I am a living avatar, not a poster.',
  'This hunt is about seeing, not labels.',
  'Wrong Meebit. Enjoy the museum anyway.',
]
