/**
 * Meebit trait dataset loaded from /data/meebit-traits.json
 * Generated by: npm run traits:fetch
 */

export type MeebitTraitMap = Record<string, string>

export type MeebitTraitsDataset = {
  version: number
  source: string
  fetchedAt: string
  count: number
  byId: Record<string, MeebitTraitMap>
}

let cachedDataset: MeebitTraitsDataset | null = null
let loadPromise: Promise<MeebitTraitsDataset | null> | null = null

export async function loadMeebitTraitsDataset(): Promise<MeebitTraitsDataset | null> {
  if (cachedDataset) {
    return cachedDataset
  }
  if (loadPromise) {
    return loadPromise
  }

  loadPromise = (async () => {
    try {
      const response = await fetch('/data/meebit-traits.json')
      if (!response.ok) {
        console.warn(`[meebitTraits] failed to load dataset (${response.status})`)
        return null
      }
      const data = (await response.json()) as MeebitTraitsDataset
      if (!data?.byId || typeof data.byId !== 'object') {
        console.warn('[meebitTraits] invalid dataset shape')
        return null
      }
      cachedDataset = data
      return data
    } catch (error) {
      console.warn('[meebitTraits] load error', error)
      return null
    } finally {
      loadPromise = null
    }
  })()

  return loadPromise
}

export function getMeebitTraitsFromDataset(
  dataset: MeebitTraitsDataset | null | undefined,
  meebitId: number,
): MeebitTraitMap | null {
  if (!dataset) return null
  return dataset.byId[String(meebitId)] ?? null
}

export async function getMeebitTraits(meebitId: number): Promise<MeebitTraitMap | null> {
  const dataset = await loadMeebitTraitsDataset()
  return getMeebitTraitsFromDataset(dataset, meebitId)
}

/** Sync lookup after dataset has been loaded (or null if not ready). */
export function getCachedMeebitTraits(meebitId: number): MeebitTraitMap | null {
  return getMeebitTraitsFromDataset(cachedDataset, meebitId)
}

export function getCachedMeebitTraitValue(meebitId: number, traitType: string): string | null {
  return getCachedMeebitTraits(meebitId)?.[traitType] ?? null
}
