/**
 * Local Meebit trait visuals under /traits/*.webp (+ solid color hex map).
 * Generated by: npm run traits:images
 *
 * Resolution mirrors meebits.com:
 * - patterned colors → shared swatch (camo.webp, …)
 * - solid colors → CSS hex
 * - tattoo yes / motif → tattoo_yes.webp
 */

export type MeebitTraitRenderManifest = {
  version: number
  source: string
  fetchedAt: string
  count: number
  bySlug: Record<string, { type: string; value: string; path: string }>
  byTraitKey: Record<string, string>
  patternColors?: Record<string, string>
}

export type MeebitTraitColorMap = {
  version: number
  source: string
  fetchedAt: string
  byTraitKeySlug: Record<string, string>
}

export type MeebitTraitVisual =
  | { kind: 'image'; path: string }
  | { kind: 'color'; hex: string }

let cachedManifest: MeebitTraitRenderManifest | null = null
let cachedColors: MeebitTraitColorMap | null = null
let manifestPromise: Promise<MeebitTraitRenderManifest | null> | null = null
let colorsPromise: Promise<MeebitTraitColorMap | null> | null = null

function slugify(text: string) {
  return text
    .replace(/['']/g, '')
    .replace(/[^a-zA-Z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .toLowerCase()
}

export function getMeebitTraitSlug(type: string, value: string) {
  return `${slugify(type)}_${slugify(value)}`
}

export async function loadMeebitTraitRenderManifest(): Promise<MeebitTraitRenderManifest | null> {
  if (cachedManifest) return cachedManifest
  if (manifestPromise) return manifestPromise

  manifestPromise = (async () => {
    try {
      const response = await fetch('/data/meebit-trait-renders.json')
      if (!response.ok) return null
      const data = (await response.json()) as MeebitTraitRenderManifest
      if (!data?.byTraitKey) return null
      cachedManifest = data
      return data
    } catch {
      return null
    } finally {
      manifestPromise = null
    }
  })()

  return manifestPromise
}

export async function loadMeebitTraitColorMap(): Promise<MeebitTraitColorMap | null> {
  if (cachedColors) return cachedColors
  if (colorsPromise) return colorsPromise

  colorsPromise = (async () => {
    try {
      const response = await fetch('/data/meebit-trait-colors.json')
      if (!response.ok) return null
      const data = (await response.json()) as MeebitTraitColorMap
      if (!data?.byTraitKeySlug) return null
      cachedColors = data
      return data
    } catch {
      return null
    } finally {
      colorsPromise = null
    }
  })()

  return colorsPromise
}

export async function resolveMeebitTraitVisual(
  type: string,
  value: string,
): Promise<MeebitTraitVisual | null> {
  if (type === 'Tattoo' && value !== 'Yes') {
    return null
  }
  if (type === 'Tattoo Motif' || (type === 'Tattoo' && value === 'Yes')) {
    return { kind: 'image', path: '/traits/tattoo_yes.webp' }
  }

  const [manifest, colors] = await Promise.all([
    loadMeebitTraitRenderManifest(),
    loadMeebitTraitColorMap(),
  ])

  const key = `${type}::${value}`
  const imagePath = manifest?.byTraitKey[key]
  if (imagePath) {
    return { kind: 'image', path: imagePath }
  }

  const colorSlug = getMeebitTraitSlug(type, value)
  const hex = colors?.byTraitKeySlug[colorSlug]
  if (hex) {
    return { kind: 'color', hex }
  }

  // Fallback for part traits before / without manifest
  if (!type.toLowerCase().includes('color') && type !== 'Tattoo Motif') {
    return { kind: 'image', path: `/traits/${colorSlug}.webp` }
  }

  return null
}

/** @deprecated Prefer resolveMeebitTraitVisual */
export async function resolveMeebitTraitRenderPath(type: string, value: string): Promise<string | null> {
  const visual = await resolveMeebitTraitVisual(type, value)
  return visual?.kind === 'image' ? visual.path : null
}
